batch:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-batch --disable-linuxmodule --disable-verbose-batch && make && make check
ip6:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-ip6 --enable-json --disable-linuxmodule --disable-batch && make && make check
mt:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --disable-linuxmodule --disable-batch && make && make check
dpdk-batch:
    script:
        - echo "RTE_SDK=$RTE_SDK RTE_TARGET=$RTE_TARGET"
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --without-netmap --enable-dpdk --disable-linuxmodule --enable-batch --disable-verbose-batch RTE_SDK=$RTE_SDK RTE_TARGET=$RTE_TARGET && make

dpdk-nobatch:
    script:
        - echo "RTE_SDK=$RTE_SDK RTE_TARGET=$RTE_TARGET"
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --without-netmap --enable-dpdk --disable-linuxmodule --disable--batch RTE_SDK=$RTE_SDK RTE_TARGET=$RTE_TARGET && make

netmap_single:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --with-netmap --disable-linuxmodule --disable-verbose-batch && make
netmap:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --with-netmap --enable-netmap-pool --enable-zerocopy --disable-linuxmodule --disable-verbose-batch && make
netmap_nopool:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --with-netmap --disable-netmap-pool --enable-zerocopy --disable-linuxmodule --disable-verbose-batch && make && make check
netmap_nopool_nozc:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --with-netmap --disable-netmap-pool --disable-zerocopy --disable-linuxmodule --disable-verbose-batch && make && make check
fbatch:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --enable-flow --enable-batch --disable-linuxmodule --disable-verbose-batch && make
fnetmap:
    script:
        - ./configure CXXFLAGS="-std=gnu++11" --enable-user-multithread --with-netmap --enable-flow --enable-batch  --enable-netmap-pool --enable-zerocopy --disable-linuxmodule --disable-verbose-batch && make

before_script:
    - gcc -v
    - if [ `sudo -n whoami` = "root" ] ; then sudo modprobe netmap && sudo chmod 666 /dev/netmap ; fi
