language: c++
env:
    matrix:
        - CONFIG=--enable-batch
        - CONFIG=--enable-user-multithread
        - CONFIG=--enable-ip6 --enable-json
compiler:
  - gcc
  - clang
script:
  - ./configure CXXFLAGS="-std=gnu++11" --disable-linuxmodule $CONFIG && make
addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - tcpdump
        - libpcap-dev
        - time
        - libnuma-dev
        - gcc-4.8
        - g++-4.8
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
sudo: false
cache: apt
