language: c++
env:
    matrix:
        - CONFIG=--enable-batch
        - CONFIG=--enable-user-multithread
        - CONFIG=--enable-ip6 --enable-json
compiler:
  - gcc
  - clang
script:
  - ./configure --disable-linuxmodule $CONFIG && make
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y tcpdump libpcap-dev time libnuma-dev
